### ISSUE TITLE
Products not being added to the cart (1.8 form_key issue)

### ISSUE THREAD

**Issue by gferon** [madepeople/Made_Cache#17]
Hi,

When Made_Cache is enabled, adding a product to the cart does not work anymore (for some products) and the Add to cart button seems to give a cached page instead of actually passing the POST request to the backend.

I think it has something to do with the fact that "After Adding a Product Redirect to Shopping Cart" is set to false. May the GET request obtained after 302 from the initial POST be cached ?

I'm still trying to investigate the issue but I'd like to know if you have any idea except excluding catalog/product/view from the cached routes.

**Comment by jonathanselander** [comment]
Fixed in d3371f8d06c22984c8e060de79e1e6fb34164ca1
