### ISSUE TITLE
Problems with ssl

### ISSUE THREAD

**Issue by jg-development** [madepeople/Made_Cache#27]
Hi,
I am using nginx for ssl termination in front of varnish and redirect all http calls to https.
The Made_Cache Extension is including the esi url with https... which ist actually bad.

However ... if I replace the https url with a http esi url, I get a redirection problem.
I enforce the magento ssl site with the config:
```xml
    <frontend>
        <secure_url>
            <all>/</all>
        </secure_url>
    </frontend>
```
in the app/etc/config.xml

Can you tell me please, which solution is the best for an enforced ssl site?
Greetings Jan

**Comment by jg-development** [comment]
The varnishlog shows me something like this:
Hash         - /home-decor/https://magento-showroom.local/madecache/varnish/esi/block/bWluaWNhcnRfaGVhZA==/hash/1/

**Comment by jonathanselander** [comment]
Hi, this commit might be relevant to you: https://github.com/madepeople/Made_Cache/commit/19e7feb6fa231be43e47bb06f4ded848530a5572
